python3 computor.py "3 * X^2 + 5 * X^1 + 7 = 0"
echo "-----------------------------------------"
python3 computor.py "4 * X^2 + 4 * X^1 = -1"
echo "-----------------------------------------"
python3 computor.py "2 * X^2 + 9 * X^1 - 5 = 0 * X^0"
echo "-----------------------------------------"
python3 computor.py "- X^2 + 2 * X^1 + 3 = 0"
echo "-----------------------------------------"
python3 computor.py "- 6 * X + X^2 - 1 = 0"
echo "-----------------------------------------"
python3 computor.py "18 * X^2 - 15 * X^1 - 3 * X^0 = 0"
echo "-----------------------------------------"
python3 computor.py "12 * X^1 + 3 = 10 * X"
echo "-----------------------------------------"
python3 computor.py "5 * X^0 + 4 * X^1 = 4 * X^0"
echo "-----------------------------------------"
python3 computor.py "42 = 42 * X^0"
echo "-----------------------------------------"
python3 computor.py "42 * X^0 = 10"
echo "-----------------------------------------"
python3 computor.py "5 * X^0 + 3 * X^1 + 3 *X^4 = 1 + 0 * X + 2*X^6"
echo
echo "----------------- ERROR ------------------"
python3 computor.py "42 * X^ = 10"
python3 computor.py " * X^0 = 10"
python3 computor.py "- * X^0 = 10"
python3 computor.py "42 X^0 = 10"
python3 computor.py "42 == 42 * X^0"
python3 computor.py "42 = = 42 * X^0"
python3 computor.py "42 = * X^0"
python3 computor.py "42 = 1 * X^0 +"
python3 computor.py "42 = 1 * "
python3 computor.py "= 1 * X^0"
python3 computor.py "4 + = 1 * X^0"
python3 computor.py "4 + o = 1 * X^0"
python3 computor.py "42 * X^0 = 10 + + 5"
python3 computor.py "42 * X^0"
